/** Uganda districts for registration, properties, filters, and user district restrictions. */
export function formatDistrictName(raw: string): string {
  return raw
    .trim()
    .toLowerCase()
    .split('-')
    .map((part) =>
      part
        .split(/\s+/)
        .filter(Boolean)
        .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
        .join(' ')
    )
    .join('-');
}

export const DISTRICTS: readonly string[] = [
  'Abim',
  'Adjumani',
  'Agago',
  'Alebtong',
  'Amolatar',
  'Amudat',
  'Amuria',
  'Amuru',
  'Apac',
  'Arua',
  'Arua City',
  'Budaka',
  'Bududa',
  'Bugiri',
  'Bugweri',
  'Buhweju',
  'Buikwe',
  'Bukedea',
  'Bukomansimbi',
  'Bukwo',
  'Bulambuli',
  'Buliisa',
  'Bundibugyo',
  'Bunyangabu',
  'Bushenyi',
  'Busia',
  'Butaleja',
  'Butambala',
  'Butebo',
  'Buvuma',
  'Buyende',
  'Dokolo',
  'Entebbe',
  'Fort Portal',
  'Fort Portal City',
  'Gomba',
  'Gulu',
  'Hoima',
  'Ibanda',
  'Iganga',
  'Isingiro',
  'Jinja',
  'Kaabong',
  'Kabale',
  'Kabarole',
  'Kaberamaido',
  'Kagadi',
  'Kakumiro',
  'Kalaki',
  'Kalangala',
  'Kaliro',
  'Kalungu',
  'Kampala',
  'Kampala Central',
  'Kamuli',
  'Kamwenge',
  'Kanungu',
  'Kapchorwa',
  'Kapelebyong',
  'Karenga',
  'Kasese',
  'Kassanda',
  'Katakwi',
  'Kawempe Division',
  'Kayunga',
  'Kazo',
  'Kibaale',
  'Kiboga',
  'Kibuku',
  'Kikuube',
  'Kiruhura',
  'Kiryandongo',
  'Kisoro',
  'Kitagwenda',
  'Kitgum',
  'Koboko',
  'Kole',
  'Kotido',
  'Kumi',
  'Kwania',
  'Kween',
  'Kyankwanzi',
  'Kyegegwa',
  'Kyenjojo',
  'Kyotera',
  'Lamwo',
  'Lira',
  'Lira City',
  'Luuka',
  'Luweero',
  'Lwengo',
  'Lyantonde',
  'Madi-Okollo',
  'Makindye Division',
  'Manafwa',
  'Maracha',
  'Masaka',
  'Masaka City',
  'Masindi',
  'Mayuge',
  'Mbale',
  'Mbale City',
  'Mbarara',
  'Mitooma',
  'Mityana',
  'Moroto',
  'Moyo',
  'Mpigi',
  'Mubende',
  'Mukono',
  'Nabilatuk',
  'Nakapiripirit',
  'Nakaseke',
  'Nakasongola',
  'Nakawa',
  'Nakawa Division',
  'Namayingo',
  'Namisindwa',
  'Namutumba',
  'Napak',
  'Nebbi',
  'Ngora',
  'Ntoroko',
  'Ntungamo',
  'Nwoya',
  'Obongi',
  'Omoro',
  'Otuke',
  'Oyam',
  'Pader',
  'Pakwach',
  'Pallisa',
  'Rakai',
  'Rubaga Division',
  'Rubanda',
  'Rubirizi',
  'Rukiga',
  'Rukungiri',
  'Rwampara',
  'Serere',
  'Sheema',
  'Sironko',
  'Soroti',
  'Soroti City',
  'Ssembabule',
  'Terego',
  'Tororo',
  'Wakiso',
  'Yumbe',
  'Zombo',
] as const;

export function isKnownDistrict(value: string): boolean {
  const v = value.trim().toLowerCase();
  return DISTRICTS.some((d) => d.toLowerCase() === v);
}
