/**
 * Real file download utilities — saves files to the user's device.
 * All functions trigger a native browser "Save As" dialog or auto-save.
 */

// ─── Core trigger ─────────────────────────────────────────────────────────────
function triggerDownload(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.style.display = 'none';
  document.body.appendChild(a);
  a.click();
  // Clean up after a short delay
  setTimeout(() => {
    URL.revokeObjectURL(url);
    document.body.removeChild(a);
  }, 150);
}

// ─── CSV export ───────────────────────────────────────────────────────────────
export function downloadCSV(rows: Record<string, unknown>[], filename: string): void {
  if (rows.length === 0) return;
  const headers = Object.keys(rows[0]);
  const escape = (v: unknown) => {
    const s = String(v ?? '').replace(/"/g, '""');
    return /[,"\n\r]/.test(s) ? `"${s}"` : s;
  };
  const csv = [
    headers.join(','),
    ...rows.map(row => headers.map(h => escape(row[h])).join(',')),
  ].join('\r\n');
  const blob = new Blob(['\uFEFF' + csv], { type: 'text/csv;charset=utf-8;' });
  triggerDownload(blob, filename.endsWith('.csv') ? filename : `${filename}.csv`);
}

// ─── PDF generation (pure HTML → print-to-PDF) ───────────────────────────────
interface PDFOptions {
  title: string;
  subtitle?: string;
  rows: { label: string; value: string; bold?: boolean; color?: string }[];
  footer?: string;
  logo?: boolean;
}

// Fetch logo as base64 for embedding in PDF
async function getLogoBase64(): Promise<string> {
  try {
    const res = await fetch('/logo.png');
    const blob = await res.blob();
    return new Promise((resolve) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result as string);
      reader.readAsDataURL(blob);
    });
  } catch {
    return '';
  }
}

export async function downloadPDF(options: PDFOptions, filename: string): Promise<void> {
  const { title, subtitle, rows, footer } = options;
  const logoBase64 = await getLogoBase64();

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <title>${title}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: 'Segoe UI', Arial, sans-serif; color: #1e293b; background: #fff; padding: 40px; }
    .header { display: flex; align-items: center; gap: 16px; margin-bottom: 32px; padding-bottom: 20px; border-bottom: 3px solid #2563eb; }
    .logo-wrap { width: 64px; height: 64px; border-radius: 12px; overflow: hidden; flex-shrink: 0; background: #f1f5f9; display: flex; align-items: center; justify-content: center; }
    .logo-wrap img { width: 100%; height: 100%; object-fit: contain; }
    .logo-fallback { width: 64px; height: 64px; background: #2563eb; border-radius: 12px; display: flex; align-items: center; justify-content: center; color: white; font-weight: 900; font-size: 20px; flex-shrink: 0; }
    .header-text h1 { font-size: 22px; font-weight: 700; color: #1e293b; }
    .header-text p { font-size: 13px; color: #64748b; margin-top: 3px; }
    .header-text .company { font-size: 12px; color: #2563eb; font-weight: 600; margin-top: 2px; }
    .subtitle { font-size: 14px; color: #64748b; margin-bottom: 24px; }
    table { width: 100%; border-collapse: collapse; }
    tr { border-bottom: 1px solid #e2e8f0; }
    tr:last-child { border-bottom: none; }
    td { padding: 10px 8px; font-size: 14px; }
    td:first-child { color: #64748b; width: 55%; }
    td:last-child { text-align: right; font-weight: 500; }
    .bold td { font-weight: 700; font-size: 15px; border-top: 2px solid #e2e8f0; }
    .green td:last-child { color: #16a34a; }
    .red td:last-child { color: #dc2626; }
    .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #e2e8f0; font-size: 12px; color: #94a3b8; text-align: center; }
    .generated { font-size: 11px; color: #cbd5e1; margin-top: 8px; }
    .watermark { position: fixed; bottom: 20px; right: 20px; opacity: 0.06; font-size: 48px; font-weight: 900; color: #2563eb; pointer-events: none; }
    @media print { body { padding: 20px; } .watermark { display: none; } }
  </style>
</head>
<body>
  <div class="header">
    ${logoBase64
      ? `<div class="logo-wrap"><img src="${logoBase64}" alt="ITAB Logo" /></div>`
      : `<div class="logo-fallback">IT</div>`
    }
    <div class="header-text">
      <h1>${title}</h1>
      ${subtitle ? `<p>${subtitle}</p>` : ''}
      <p class="company">ITAB Property Services · Uganda</p>
    </div>
  </div>
  <table>
    ${rows.map(r => `
      <tr class="${r.bold ? 'bold' : ''} ${r.color === 'green' ? 'green' : r.color === 'red' ? 'red' : ''}">
        <td>${r.label}</td>
        <td>${r.value}</td>
      </tr>`).join('')}
  </table>
  ${footer ? `<div class="footer">${footer}</div>` : ''}
  <div class="generated">Generated by ITAB Property Services · ${new Date().toLocaleString('en-UG')}</div>
  <div class="watermark">ITAB</div>
</body>
</html>`;

  const blob = new Blob([html], { type: 'text/html;charset=utf-8;' });
  triggerDownload(blob, filename.endsWith('.html') ? filename : `${filename}.html`);

  // Open print dialog for true PDF saving
  const printWindow = window.open('', '_blank', 'width=800,height=600');
  if (printWindow) {
    printWindow.document.write(html);
    printWindow.document.close();
    printWindow.onload = () => {
      setTimeout(() => {
        printWindow.print();
        printWindow.close();
      }, 300);
    };
  }
}

// ─── Receipt ──────────────────────────────────────────────────────────────────
export interface ReceiptData {
  reference: string;
  type: string;
  propertyTitle: string;
  tenantName?: string;
  amount: number;
  method: string;
  date: string;
  inspectionCredit?: number;
  rentPeriod?: string;
  isPartial?: boolean;
  remainingBalance?: number;
}

export async function downloadReceipt(data: ReceiptData): Promise<void> {
  const fmt = (n: number) => new Intl.NumberFormat('en-UG', { style: 'currency', currency: 'UGX', minimumFractionDigits: 0 }).format(n);

  const rows: PDFOptions['rows'] = [
    { label: 'Receipt Reference', value: data.reference },
    { label: 'Payment Type', value: data.type },
    { label: 'Property', value: data.propertyTitle },
    ...(data.tenantName ? [{ label: 'Tenant', value: data.tenantName }] : []),
    ...(data.rentPeriod ? [{ label: 'Rent Period', value: data.rentPeriod }] : []),
    { label: 'Payment Method', value: data.method },
    { label: 'Date Paid', value: new Date(data.date).toLocaleString('en-UG') },
    ...(data.inspectionCredit ? [{ label: 'Inspection Credit Applied', value: `-${fmt(data.inspectionCredit)}`, color: 'green' as const }] : []),
    { label: 'Amount Paid', value: fmt(data.amount), bold: true, color: 'green' as const },
    ...(data.isPartial && data.remainingBalance !== undefined
      ? [{ label: 'Remaining Balance', value: fmt(data.remainingBalance), color: 'red' as const }]
      : []),
  ];

  await downloadPDF({
    title: 'Payment Receipt',
    subtitle: `ITAB Property Services · ${data.reference}`,
    rows,
    footer: data.isPartial
      ? '⚠️ This is a partial payment. The remaining balance is still outstanding.'
      : '✅ Payment confirmed. Thank you for using ITAB Property Services.',
  }, `receipt-${data.reference}`);
}

// ─── Financial Statement ──────────────────────────────────────────────────────
export interface StatementData {
  landlordName: string;
  period: string;
  properties: {
    title: string;
    grossRent: number;
    managementFee: number;
    itabFee: number;
    netPayout: number;
    inspectionCredits?: number;
  }[];
}

export async function downloadStatement(data: StatementData): Promise<void> {
  const fmt = (n: number) => new Intl.NumberFormat('en-UG', { style: 'currency', currency: 'UGX', minimumFractionDigits: 0 }).format(n);
  const totalGross = data.properties.reduce((s, p) => s + p.grossRent, 0);
  const totalMgmt = data.properties.reduce((s, p) => s + p.managementFee, 0);
  const totalItab = data.properties.reduce((s, p) => s + p.itabFee, 0);
  const totalNet = data.properties.reduce((s, p) => s + p.netPayout, 0);

  const rows: PDFOptions['rows'] = [
    { label: 'Landlord', value: data.landlordName },
    { label: 'Statement Period', value: data.period },
    { label: '', value: '' },
    ...data.properties.flatMap(p => [
      { label: `📍 ${p.title}`, value: '' },
      { label: '  Gross Rent', value: fmt(p.grossRent) },
      { label: '  Management Fee', value: `-${fmt(p.managementFee)}`, color: 'red' as const },
      { label: '  ITAB Platform Fee', value: `-${fmt(p.itabFee)}`, color: 'red' as const },
      { label: '  Net Payout', value: fmt(p.netPayout), color: 'green' as const },
    ]),
    { label: '', value: '' },
    { label: 'TOTAL Gross Rent', value: fmt(totalGross) },
    { label: 'TOTAL Fees Deducted', value: `-${fmt(totalMgmt + totalItab)}`, color: 'red' as const },
    { label: 'TOTAL Net Payout', value: fmt(totalNet), bold: true, color: 'green' as const },
  ];

  await downloadPDF({
    title: `Financial Statement — ${data.period}`,
    subtitle: `Prepared for ${data.landlordName}`,
    rows,
    footer: 'This statement is for informational purposes. Please retain for your tax records.',
  }, `statement-${data.period.replace(/\s+/g, '-')}`);
}

// ─── Payout Report ────────────────────────────────────────────────────────────
export function downloadPayoutReport(payouts: {
  id: string; landlordName: string; propertyTitle: string;
  grossRent: number; managementFee: number; itabFee: number;
  netAmount: number; status: string; method: string; processedAt?: string;
}[]): void {
  downloadCSV(payouts.map(p => ({
    'Reference': p.id,
    'Landlord': p.landlordName,
    'Property': p.propertyTitle,
    'Gross Rent (UGX)': p.grossRent,
    'Management Fee (UGX)': p.managementFee,
    'ITAB Fee (UGX)': p.itabFee,
    'Net Payout (UGX)': p.netAmount,
    'Status': p.status,
    'Method': p.method,
    'Processed At': p.processedAt || 'Pending',
  })), `payout-report-${new Date().toISOString().split('T')[0]}`);
}

// ─── Payments CSV ─────────────────────────────────────────────────────────────
export function downloadPaymentsCSV(payments: {
  reference: string; type: string; propertyTitle: string;
  amount: number; method: string; status: string;
  tenantName?: string; rentPeriod?: string; paidAt?: string;
}[]): void {
  downloadCSV(payments.map(p => ({
    'Reference': p.reference,
    'Type': p.type,
    'Property': p.propertyTitle,
    'Tenant': p.tenantName || '',
    'Rent Period': p.rentPeriod || '',
    'Amount (UGX)': p.amount,
    'Method': p.method,
    'Status': p.status,
    'Date': p.paidAt || '',
  })), `payments-${new Date().toISOString().split('T')[0]}`);
}

// ─── Lease document ───────────────────────────────────────────────────────────
export async function downloadLease(data: {
  tenantName: string; propertyTitle: string; address: string;
  rentAmount: number; depositAmount: number; leaseStart: string;
  leaseEnd: string; managerName: string;
}): Promise<void> {
  const fmt = (n: number) => new Intl.NumberFormat('en-UG', { style: 'currency', currency: 'UGX', minimumFractionDigits: 0 }).format(n);
  await downloadPDF({
    title: 'Tenancy Agreement',
    subtitle: `${data.propertyTitle} · ${data.address}`,
    rows: [
      { label: 'Tenant Name', value: data.tenantName },
      { label: 'Property', value: data.propertyTitle },
      { label: 'Address', value: data.address },
      { label: 'Monthly Rent', value: fmt(data.rentAmount) },
      { label: 'Security Deposit', value: fmt(data.depositAmount) },
      { label: 'Lease Start Date', value: new Date(data.leaseStart).toLocaleDateString('en-UG') },
      { label: 'Lease End Date', value: new Date(data.leaseEnd).toLocaleDateString('en-UG') },
      { label: 'Property Manager', value: data.managerName },
      { label: 'Status', value: 'Active', bold: true, color: 'green' },
    ],
    footer: 'This document is a summary of your tenancy agreement. The full signed agreement is on file with your property manager.',
  }, `lease-${data.tenantName.replace(/\s+/g, '-')}`);
}
